spring:
  datasource:
    url: https://press-lab-d3e63a641e78.herokuapp.com/
    username: postgres
    password: alma

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
file:
  upload-dir: /path/to/upload/directory
